// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuxqxjwbpbwourkblhte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1eHF4andicGJ3b3Vya2JsaHRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDc3MDAsImV4cCI6MjA2Mjk4MzcwMH0.l1Agp4-qw4vSIyelQokYH0R1UfDhgo8hQSZRAMpNYRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);